development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: patentlookup
  pool: 5
  username: aknicol
  password: thEY5paw
  host: patentlookup.cmgoqepvat3h.us-east-1.rds.amazonaws.com
